server:
  port: 8080
  max-http-header-size: 16384

FRONTEND_URL: ${FRONTEND_URL}

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.hhkfampfwegztabrpffn
    password: Imation@STC@123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: mySecretKey
  expiration: 86400000

gemini:
  api-key: AIzaSyBVsNDe932oyO6kBXm-oQ-NoFJspV4x4jM
  model: gemini-2.5-flash
  api-url: https://generativelanguage.googleapis.com/v1beta
